'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
'
Namespace biz.plane.www
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ExchangeConnectSoap", [Namespace]:="http://www.plane.biz/exchange/20060125/ExchangeConnect")>  _
    Public Class ExchangeConnect
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Public HeaderInfoValue As HeaderInfo
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://demo.plane.biz/Exchange2/ExchangeConnect.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("HeaderInfoValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.plane.biz/exchange/20060125/ExchangeConnect/GetExchangeStatus", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetExchangeStatus(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/employeeinfo")> ByVal Employee As Employee, <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/benefitinfo", IsNullable:=true)> ByVal BenefitInfo As BenefitInfo, <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/htmllayoutinfo", IsNullable:=true)> ByVal HTMLLayout As HTMLLayout, <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoemployee")> ByVal LogonEmployee As LogonEmployee, <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoenroller", IsNullable:=true)> ByVal LogonEnroller As LogonEnroller, <System.Xml.Serialization.XmlArrayAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/dependentinfo", IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute("Dependent", [Namespace]:="http://www.plane.biz/exchange/20060125/dependentinfo", IsNullable:=false)> ByVal Dependents() As DependentsDependent, <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/hostinfo", IsNullable:=true)> ByVal HostURL As HostURL) As <System.Xml.Serialization.XmlElementAttribute("InitReturn", [Namespace]:="http://www.plane.biz/exchange/20060125/initreturn")> InitReturn
            Dim results() As Object = Me.Invoke("GetExchangeStatus", New Object() {Employee, BenefitInfo, HTMLLayout, LogonEmployee, LogonEnroller, Dependents, HostURL})
            Return CType(results(0),InitReturn)
        End Function
        
        '<remarks/>
        Public Function BeginGetExchangeStatus(ByVal Employee As Employee, ByVal BenefitInfo As BenefitInfo, ByVal HTMLLayout As HTMLLayout, ByVal LogonEmployee As LogonEmployee, ByVal LogonEnroller As LogonEnroller, ByVal Dependents() As DependentsDependent, ByVal HostURL As HostURL, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetExchangeStatus", New Object() {Employee, BenefitInfo, HTMLLayout, LogonEmployee, LogonEnroller, Dependents, HostURL}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetExchangeStatus(ByVal asyncResult As System.IAsyncResult) As InitReturn
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),InitReturn)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("HeaderInfoValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.plane.biz/exchange/20060125/ExchangeConnect/GetExchangeSessionStatus", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetExchangeSessionStatus(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/sessionstatus")> ByVal SessionStatusIn As SessionStatusIn) As <System.Xml.Serialization.XmlElementAttribute("SessionStatusOut", [Namespace]:="http://www.plane.biz/exchange/20060125/sessionstatus")> SessionStatusOut
            Dim results() As Object = Me.Invoke("GetExchangeSessionStatus", New Object() {SessionStatusIn})
            Return CType(results(0),SessionStatusOut)
        End Function
        
        '<remarks/>
        Public Function BeginGetExchangeSessionStatus(ByVal SessionStatusIn As SessionStatusIn, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetExchangeSessionStatus", New Object() {SessionStatusIn}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetExchangeSessionStatus(ByVal asyncResult As System.IAsyncResult) As SessionStatusOut
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SessionStatusOut)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("HeaderInfoValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.plane.biz/exchange/20060125/ExchangeConnect/GetExchangeEnrollmentSumma"& _ 
"ry", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function GetExchangeEnrollmentSummary(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummaryParameters")> ByVal EnrollmentSummaryParameters As EnrollmentSummaryParameters) As <System.Xml.Serialization.XmlElementAttribute("EnrollmentData", [Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")> EnrollmentData
            Dim results() As Object = Me.Invoke("GetExchangeEnrollmentSummary", New Object() {EnrollmentSummaryParameters})
            Return CType(results(0),EnrollmentData)
        End Function
        
        '<remarks/>
        Public Function BeginGetExchangeEnrollmentSummary(ByVal EnrollmentSummaryParameters As EnrollmentSummaryParameters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetExchangeEnrollmentSummary", New Object() {EnrollmentSummaryParameters}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetExchangeEnrollmentSummary(ByVal asyncResult As System.IAsyncResult) As EnrollmentData
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),EnrollmentData)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/headerinfo"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/headerinfo", IsNullable:=false)>  _
    Public Class HeaderInfo
        Inherits System.Web.Services.Protocols.SoapHeader
        
        '<remarks/>
        Public EmployerID As System.Guid
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class EnrollmentDataExistingBenefit
        
        '<remarks/>
        Public ProductDescription As String
        
        '<remarks/>
        Public InsuredName As String
        
        '<remarks/>
        Public ProductID As String
        
        '<remarks/>
        Public Premium As Premium
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class Premium
        
        '<remarks/>
        Public Annual As Decimal
        
        '<remarks/>
        Public PayPeriod As Decimal
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class EnrollmentDataPersonBenefitCoverageDetailsEliminationBenefitPeriod
        
        '<remarks/>
        Public AccidentEliminationPeriod As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public AccidentEliminationPeriodSpecified As Boolean
        
        '<remarks/>
        Public SicknessEliminationPeriod As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public SicknessEliminationPeriodSpecified As Boolean
        
        '<remarks/>
        Public BenefitPeriod As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public BenefitPeriodSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class EnrollmentDataPersonBenefitCoverageDetails
        
        '<remarks/>
        Public Description As String
        
        '<remarks/>
        Public Plan As String
        
        '<remarks/>
        Public Premium As Premium
        
        '<remarks/>
        Public CoverageAmount As Decimal
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public CoverageAmountSpecified As Boolean
        
        '<remarks/>
        Public EliminationBenefitPeriod As EnrollmentDataPersonBenefitCoverageDetailsEliminationBenefitPeriod
        
        '<remarks/>
        Public Units As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public UnitsSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class EnrollmentDataPersonBenefit
        
        '<remarks/>
        Public Description As String
        
        '<remarks/>
        Public Status As BenefitStatus
        
        '<remarks/>
        Public ProductID As String
        
        '<remarks/>
        Public CoverageBeginDate As Date
        
        '<remarks/>
        Public CoverageChangeDate As Date
        
        '<remarks/>
        Public CoverageEndDate As Date
        
        '<remarks/>
        Public FirstDeductionDate As Date
        
        '<remarks/>
        Public PreTaxBenefitPremiumEmployee As Premium
        
        '<remarks/>
        Public AfterTaxBenefitPremiumEmployee As Premium
        
        '<remarks/>
        Public TotalBenefitPremiumEmployee As Premium
        
        '<remarks/>
        Public TotalBenefitPremiumEmployer As Premium
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("CoverageDetails", IsNullable:=false)>  _
        Public Coverages() As EnrollmentDataPersonBenefitCoverageDetails
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Enum BenefitStatus
        
        '<remarks/>
        Complete
        
        '<remarks/>
        Decline
        
        '<remarks/>
        Incomplete
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Kit Requested")>  _
        KitRequested
        
        '<remarks/>
        Maintain
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Not Eligible")>  _
        NotEligible
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Opt-Out")>  _
        OptOut
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Paper Application")>  _
        PaperApplication
        
        '<remarks/>
        Rejected
        
        '<remarks/>
        Waive
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class ExtendedDependentDemographicData
        
        '<remarks/>
        Public SchoolName As String
        
        '<remarks/>
        Public DependentStatus As ESDependentStatusList
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Enum ESDependentStatusList
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N\A")>  _
        NA
        
        '<remarks/>
        Handicap
        
        '<remarks/>
        Student
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Handicap-Student")>  _
        HandicapStudent
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class ExtendedEmployeeDemographicData
        
        '<remarks/>
        Public EmployeeNumber As String
        
        '<remarks/>
        Public LocationID As Integer
        
        '<remarks/>
        Public ClassID As Integer
        
        '<remarks/>
        Public MaidenName As String
        
        '<remarks/>
        Public Country As String
        
        '<remarks/>
        Public Fax As String
        
        '<remarks/>
        Public Suffix As String
        
        '<remarks/>
        Public Salary As Decimal
        
        '<remarks/>
        Public HeightFeet As Integer
        
        '<remarks/>
        Public HeightInches As Integer
        
        '<remarks/>
        Public Weight As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public HireDate As Date
        
        '<remarks/>
        Public BillUnit As String
        
        '<remarks/>
        Public HoursWorkedPerWeek As Decimal
        
        '<remarks/>
        Public Bonus As Decimal
        
        '<remarks/>
        Public BirthCountry As String
        
        '<remarks/>
        Public Duties As String
        
        '<remarks/>
        Public AnnualWorkDays As Integer
        
        '<remarks/>
        Public PinCode As String
        
        '<remarks/>
        Public County As String
        
        '<remarks/>
        Public Department As String
        
        '<remarks/>
        Public PayType As ESPayTypeList
        
        '<remarks/>
        Public Shift As String
        
        '<remarks/>
        Public TaxRate As Decimal
        
        '<remarks/>
        Public LocationInfo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Enum ESPayTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N/A")>  _
        NA
        
        '<remarks/>
        Unknown
        
        '<remarks/>
        Hourly
        
        '<remarks/>
        Salary
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class EnrollmentDataPerson
        
        '<remarks/>
        Public SSN As String
        
        '<remarks/>
        Public Title As String
        
        '<remarks/>
        Public FirstName As String
        
        '<remarks/>
        Public LastName As String
        
        '<remarks/>
        Public MiddleName As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public DateofBirth As Date
        
        '<remarks/>
        Public Gender As EnrollmentDataPersonGender
        
        '<remarks/>
        Public MaritalStatus As EnrollmentDataPersonMaritalStatus
        
        '<remarks/>
        Public Address1 As String
        
        '<remarks/>
        Public Address2 As String
        
        '<remarks/>
        Public City As String
        
        '<remarks/>
        Public State As String
        
        '<remarks/>
        Public Zip As String
        
        '<remarks/>
        Public HomePhone As String
        
        '<remarks/>
        Public WorkPhone As String
        
        '<remarks/>
        Public EMail As String
        
        '<remarks/>
        Public Occupation As String
        
        '<remarks/>
        Public BirthState As String
        
        '<remarks/>
        Public Relationship As ESDependentRelationType
        
        '<remarks/>
        Public ExtendedEmployeeDemographicData As ExtendedEmployeeDemographicData
        
        '<remarks/>
        Public ExtendedDependentDemographicData As ExtendedDependentDemographicData
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Benefit", IsNullable:=false)>  _
        Public Benefits() As EnrollmentDataPersonBenefit
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Enum EnrollmentDataPersonGender
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N/A")>  _
        NA
        
        '<remarks/>
        Male
        
        '<remarks/>
        Female
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Enum EnrollmentDataPersonMaritalStatus
        
        '<remarks/>
        Unknown
        
        '<remarks/>
        [Single]
        
        '<remarks/>
        Married
        
        '<remarks/>
        Divorced
        
        '<remarks/>
        Separated
        
        '<remarks/>
        Widow
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N/A")>  _
        NA
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Enum ESDependentRelationType
        
        '<remarks/>
        Employee
        
        '<remarks/>
        Child
        
        '<remarks/>
        Spouse
        
        '<remarks/>
        Father
        
        '<remarks/>
        Mother
        
        '<remarks/>
        Friends
        
        '<remarks/>
        Others
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner")>  _
        DomesticPartner
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Grand Child")>  _
        GrandChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Foster Child")>  _
        FosterChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Step Child")>  _
        StepChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Grand Father")>  _
        GrandFather
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Grand Mother")>  _
        GrandMother
        
        '<remarks/>
        Niece
        
        '<remarks/>
        Nephew
        
        '<remarks/>
        Sister
        
        '<remarks/>
        Brother
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Sister-in-law")>  _
        Sisterinlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Brother-in-law")>  _
        Brotherinlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Father-in-law")>  _
        Fatherinlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Mother-in-law")>  _
        Motherinlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Adopted Child")>  _
        AdoptedChild
        
        '<remarks/>
        Cousin
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Ex-Spouse")>  _
        ExSpouse
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Sponsored Dependent")>  _
        SponsoredDependent
        
        '<remarks/>
        Guardian
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Court Appointed Guardian")>  _
        CourtAppointedGuardian
        
        '<remarks/>
        Ward
        
        '<remarks/>
        Stepfather
        
        '<remarks/>
        Stepmother
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Collateral Dependent")>  _
        CollateralDependent
        
        '<remarks/>
        Self
        
        '<remarks/>
        Aunt
        
        '<remarks/>
        Uncle
        
        '<remarks/>
        Parent
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Non-relation")>  _
        Nonrelation
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner's Child")>  _
        DomesticPartnersChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner's Step Child")>  _
        DomesticPartnersStepChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner's Adopted Child")>  _
        DomesticPartnersAdoptedChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner's Foster Child")>  _
        DomesticPartnersFosterChild
        
        '<remarks/>
        Husband
        
        '<remarks/>
        Wife
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Son-in-law")>  _
        Soninlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Daughter-in-law")>  _
        Daughterinlaw
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummary")>  _
    Public Class EnrollmentData
        
        '<remarks/>
        Public ExchangeData As String
        
        '<remarks/>
        Public PublicVersion As String
        
        '<remarks/>
        Public DBVersion As String
        
        '<remarks/>
        Public CaseVersion As String
        
        '<remarks/>
        Public Deductions As Integer
        
        '<remarks/>
        Public TotalPremiumEmployee As Premium
        
        '<remarks/>
        Public TotalPremiumEmployer As Premium
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Person", IsNullable:=false)>  _
        Public Persons() As EnrollmentDataPerson
        
        '<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ExistingBenefit", IsNullable:=false)>  _
        Public ExistingCoverage() As EnrollmentDataExistingBenefit
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummaryParameters")>  _
    Public Class EnrollmentSummaryParameters
        
        '<remarks/>
        Public SessionID As String
        
        '<remarks/>
        Public BenefitType As ESBenefitTypeList
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060201/EnrollmentSummaryParameters")>  _
    Public Enum ESBenefitTypeList
        
        '<remarks/>
        All
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Group Long Term Care 2004")>  _
        GroupLongTermCare2004
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Group LTC")>  _
        GroupLTC
        
        '<remarks/>
        IIP
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Interest Sensitive Whole Life")>  _
        InterestSensitiveWholeLife
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Specified Critical Illness")>  _
        SpecifiedCriticalIllness
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-Accident")>  _
        VWBAccident
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-STD")>  _
        VWBSTD
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-IUL")>  _
        VWBIUL
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-Term Life")>  _
        VWBTermLife
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-MedSupport")>  _
        VWBMedSupport
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/sessionstatus")>  _
    Public Class SessionStatusOut
        
        '<remarks/>
        Public Status As StatusList
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/sessionstatus")>  _
    Public Enum StatusList
        
        '<remarks/>
        [True]
        
        '<remarks/>
        [False]
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/sessionstatus")>  _
    Public Class SessionStatusIn
        
        '<remarks/>
        Public SessionID As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/initreturn")>  _
    Public Class InitReturn
        
        '<remarks/>
        Public SessionID As String
        
        '<remarks/>
        Public ExchangeURL As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/hostinfo")>  _
    Public Class HostURL
        
        '<remarks/>
        Public ReturnURL As String
        
        '<remarks/>
        Public ExceptionURL As String
        
        '<remarks/>
        Public TimeoutURL As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/dependentinfo")>  _
    Public Class DependentsDependent
        
        '<remarks/>
        Public SSN As String
        
        '<remarks/>
        Public Title As String
        
        '<remarks/>
        Public FirstName As String
        
        '<remarks/>
        Public LastName As String
        
        '<remarks/>
        Public MiddleName As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public DateOfBirth As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public DateOfBirthSpecified As Boolean
        
        '<remarks/>
        Public Gender As DependentsDependentGender
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public GenderSpecified As Boolean
        
        '<remarks/>
        Public MaritalStatus As DependentsDependentMaritalStatus
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public MaritalStatusSpecified As Boolean
        
        '<remarks/>
        Public RelationType As DependentRelationType
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public RelationTypeSpecified As Boolean
        
        '<remarks/>
        Public Address1 As String
        
        '<remarks/>
        Public Address2 As String
        
        '<remarks/>
        Public City As String
        
        '<remarks/>
        Public State As DependentStateList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public StateSpecified As Boolean
        
        '<remarks/>
        Public Zip As String
        
        '<remarks/>
        Public HomePhone As String
        
        '<remarks/>
        Public WorkPhone As String
        
        '<remarks/>
        Public EMail As String
        
        '<remarks/>
        Public Occupation As String
        
        '<remarks/>
        Public SchoolName As String
        
        '<remarks/>
        Public DependentStatus As DependentStatusList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public DependentStatusSpecified As Boolean
        
        '<remarks/>
        Public DataChangeDate As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/dependentinfo")>  _
    Public Enum DependentsDependentGender
        
        '<remarks/>
        Male
        
        '<remarks/>
        Female
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/dependentinfo")>  _
    Public Enum DependentsDependentMaritalStatus
        
        '<remarks/>
        Unknown
        
        '<remarks/>
        [Single]
        
        '<remarks/>
        Married
        
        '<remarks/>
        Divorced
        
        '<remarks/>
        Separated
        
        '<remarks/>
        Widow
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/dependentinfo")>  _
    Public Enum DependentRelationType
        
        '<remarks/>
        Employee
        
        '<remarks/>
        Child
        
        '<remarks/>
        Spouse
        
        '<remarks/>
        Father
        
        '<remarks/>
        Mother
        
        '<remarks/>
        Friends
        
        '<remarks/>
        Others
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner")>  _
        DomesticPartner
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Grand Child")>  _
        GrandChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Foster Child")>  _
        FosterChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Step Child")>  _
        StepChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Grand Father")>  _
        GrandFather
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Grand Mother")>  _
        GrandMother
        
        '<remarks/>
        Niece
        
        '<remarks/>
        Nephew
        
        '<remarks/>
        Sister
        
        '<remarks/>
        Brother
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Sister-in-law")>  _
        Sisterinlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Brother-in-law")>  _
        Brotherinlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Father-in-law")>  _
        Fatherinlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Mother-in-law")>  _
        Motherinlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Adopted Child")>  _
        AdoptedChild
        
        '<remarks/>
        Cousin
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Ex-Spouse")>  _
        ExSpouse
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Sponsored Dependent")>  _
        SponsoredDependent
        
        '<remarks/>
        Guardian
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Court Appointed Guardian")>  _
        CourtAppointedGuardian
        
        '<remarks/>
        Ward
        
        '<remarks/>
        Stepfather
        
        '<remarks/>
        Stepmother
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Collateral Dependent")>  _
        CollateralDependent
        
        '<remarks/>
        Self
        
        '<remarks/>
        Aunt
        
        '<remarks/>
        Uncle
        
        '<remarks/>
        Parent
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Non-relation")>  _
        Nonrelation
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner's Child")>  _
        DomesticPartnersChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner's Step Child")>  _
        DomesticPartnersStepChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner's Adopted Child")>  _
        DomesticPartnersAdoptedChild
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Domestic Partner's Foster Child")>  _
        DomesticPartnersFosterChild
        
        '<remarks/>
        Husband
        
        '<remarks/>
        Wife
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Son-in-law")>  _
        Soninlaw
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Daughter-in-law")>  _
        Daughterinlaw
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/dependentinfo")>  _
    Public Enum DependentStateList
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("")>  _
        Item
        
        '<remarks/>
        AK
        
        '<remarks/>
        AL
        
        '<remarks/>
        AR
        
        '<remarks/>
        AZ
        
        '<remarks/>
        BC
        
        '<remarks/>
        CA
        
        '<remarks/>
        CO
        
        '<remarks/>
        CT
        
        '<remarks/>
        DC
        
        '<remarks/>
        DE
        
        '<remarks/>
        FL
        
        '<remarks/>
        GA
        
        '<remarks/>
        GU
        
        '<remarks/>
        HI
        
        '<remarks/>
        IA
        
        '<remarks/>
        ID
        
        '<remarks/>
        IL
        
        '<remarks/>
        [IN]
        
        '<remarks/>
        KS
        
        '<remarks/>
        KY
        
        '<remarks/>
        LA
        
        '<remarks/>
        MA
        
        '<remarks/>
        MD
        
        '<remarks/>
        [ME]
        
        '<remarks/>
        MI
        
        '<remarks/>
        MN
        
        '<remarks/>
        MO
        
        '<remarks/>
        MS
        
        '<remarks/>
        MT
        
        '<remarks/>
        NA
        
        '<remarks/>
        NC
        
        '<remarks/>
        ND
        
        '<remarks/>
        NE
        
        '<remarks/>
        NH
        
        '<remarks/>
        NJ
        
        '<remarks/>
        NM
        
        '<remarks/>
        NV
        
        '<remarks/>
        NY
        
        '<remarks/>
        OH
        
        '<remarks/>
        OK
        
        '<remarks/>
        [ON]
        
        '<remarks/>
        [OR]
        
        '<remarks/>
        PA
        
        '<remarks/>
        PR
        
        '<remarks/>
        RI
        
        '<remarks/>
        SC
        
        '<remarks/>
        SD
        
        '<remarks/>
        TN
        
        '<remarks/>
        TX
        
        '<remarks/>
        UT
        
        '<remarks/>
        VA
        
        '<remarks/>
        VI
        
        '<remarks/>
        VT
        
        '<remarks/>
        WA
        
        '<remarks/>
        WI
        
        '<remarks/>
        WV
        
        '<remarks/>
        WY
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/dependentinfo")>  _
    Public Enum DependentStatusList
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N\A")>  _
        NA
        
        '<remarks/>
        Handicap
        
        '<remarks/>
        Student
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Handicap-Student")>  _
        HandicapStudent
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoenroller")>  _
    Public Class LogonEnroller
        
        '<remarks/>
        Public LogonName As String
        
        '<remarks/>
        Public FirstName As String
        
        '<remarks/>
        Public MiddleName As String
        
        '<remarks/>
        Public LastName As String
        
        '<remarks/>
        Public EnrollmentCity As String
        
        '<remarks/>
        Public EnrollmentState As EnrollerStateList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public EnrollmentStateSpecified As Boolean
        
        '<remarks/>
        Public LogonType As LogonTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public LogonTypeSpecified As Boolean
        
        '<remarks/>
        Public AuthenticationType As EnrollerAuthenticationTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public AuthenticationTypeSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoenroller")>  _
    Public Enum EnrollerStateList
        
        '<remarks/>
        AK
        
        '<remarks/>
        AL
        
        '<remarks/>
        AR
        
        '<remarks/>
        AZ
        
        '<remarks/>
        BC
        
        '<remarks/>
        CA
        
        '<remarks/>
        CO
        
        '<remarks/>
        CT
        
        '<remarks/>
        DC
        
        '<remarks/>
        DE
        
        '<remarks/>
        FL
        
        '<remarks/>
        GA
        
        '<remarks/>
        GU
        
        '<remarks/>
        HI
        
        '<remarks/>
        IA
        
        '<remarks/>
        ID
        
        '<remarks/>
        IL
        
        '<remarks/>
        [IN]
        
        '<remarks/>
        KS
        
        '<remarks/>
        KY
        
        '<remarks/>
        LA
        
        '<remarks/>
        MA
        
        '<remarks/>
        MD
        
        '<remarks/>
        [ME]
        
        '<remarks/>
        MI
        
        '<remarks/>
        MN
        
        '<remarks/>
        MO
        
        '<remarks/>
        MS
        
        '<remarks/>
        MT
        
        '<remarks/>
        NA
        
        '<remarks/>
        NC
        
        '<remarks/>
        ND
        
        '<remarks/>
        NE
        
        '<remarks/>
        NH
        
        '<remarks/>
        NJ
        
        '<remarks/>
        NM
        
        '<remarks/>
        NV
        
        '<remarks/>
        NY
        
        '<remarks/>
        OH
        
        '<remarks/>
        OK
        
        '<remarks/>
        [ON]
        
        '<remarks/>
        [OR]
        
        '<remarks/>
        PA
        
        '<remarks/>
        PR
        
        '<remarks/>
        RI
        
        '<remarks/>
        SC
        
        '<remarks/>
        SD
        
        '<remarks/>
        TN
        
        '<remarks/>
        TX
        
        '<remarks/>
        UT
        
        '<remarks/>
        VA
        
        '<remarks/>
        VI
        
        '<remarks/>
        VT
        
        '<remarks/>
        WA
        
        '<remarks/>
        WI
        
        '<remarks/>
        WV
        
        '<remarks/>
        WY
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoenroller")>  _
    Public Enum LogonTypeList
        
        '<remarks/>
        Enroller
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Call Center - UPC")>  _
        CallCenterUPC
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Call Center - Other")>  _
        CallCenterOther
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoenroller")>  _
    Public Enum EnrollerAuthenticationTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Signature Pad")>  _
        SignaturePad
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Voice - UPC")>  _
        VoiceUPC
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Voice - Other")>  _
        VoiceOther
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoemployee")>  _
    Public Class LogonEmployee
        
        '<remarks/>
        Public IDKey As LogonEmployeeIDKey
        
        '<remarks/>
        Public AuthenticationType As EmployeeAuthenticationTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public AuthenticationTypeSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoemployee")>  _
    Public Enum LogonEmployeeIDKey
        
        '<remarks/>
        SSN
        
        '<remarks/>
        EmployeeNumber
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/logoninfoemployee")>  _
    Public Enum EmployeeAuthenticationTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("E-Signature")>  _
        ESignature
        
        '<remarks/>
        PIN
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Signature Pad")>  _
        SignaturePad
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Voice - UPC")>  _
        VoiceUPC
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Voice - Other")>  _
        VoiceOther
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/htmllayoutinfo")>  _
    Public Class HTMLLayout
        
        '<remarks/>
        Public Top As String
        
        '<remarks/>
        Public Left As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/benefitinfo")>  _
    Public Class BenefitInfo
        
        '<remarks/>
        Public BenefitType As BenefitTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public BenefitTypeSpecified As Boolean
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/benefitinfo")>  _
    Public Enum BenefitTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Group Long Term Care 2004")>  _
        GroupLongTermCare2004
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Group LTC")>  _
        GroupLTC
        
        '<remarks/>
        IIP
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Interest Sensitive Whole Life")>  _
        InterestSensitiveWholeLife
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Specified Critical Illness")>  _
        SpecifiedCriticalIllness
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-Accident")>  _
        VWBAccident
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-STD")>  _
        VWBSTD
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-IUL")>  _
        VWBIUL
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-Term Life")>  _
        VWBTermLife
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("VWB-MedSupport")>  _
        VWBMedSupport
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/employeeinfo")>  _
    Public Class Employee
        
        '<remarks/>
        Public SSN As String
        
        '<remarks/>
        Public EmployeeNumber As String
        
        '<remarks/>
        Public Title As String
        
        '<remarks/>
        Public FirstName As String
        
        '<remarks/>
        Public LastName As String
        
        '<remarks/>
        Public MiddleName As String
        
        '<remarks/>
        Public NameSuffix As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public DateOfBirth As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public DateOfBirthSpecified As Boolean
        
        '<remarks/>
        Public BirthCountry As String
        
        '<remarks/>
        Public BirthState As EmployeeStateList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public BirthStateSpecified As Boolean
        
        '<remarks/>
        Public LengthUSResidence As String
        
        '<remarks/>
        Public Gender As EmployeeGender
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public GenderSpecified As Boolean
        
        '<remarks/>
        Public MaritalStatus As EmployeeMaritalStatus
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public MaritalStatusSpecified As Boolean
        
        '<remarks/>
        Public [Class] As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public ClassSpecified As Boolean
        
        '<remarks/>
        Public Location As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public LocationSpecified As Boolean
        
        '<remarks/>
        Public Address1 As String
        
        '<remarks/>
        Public Address2 As String
        
        '<remarks/>
        Public City As String
        
        '<remarks/>
        Public State As EmployeeStateList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public StateSpecified As Boolean
        
        '<remarks/>
        Public Zip As String
        
        '<remarks/>
        Public Country As String
        
        '<remarks/>
        Public HomePhone As String
        
        '<remarks/>
        Public WorkPhone As String
        
        '<remarks/>
        Public Fax As String
        
        '<remarks/>
        Public Email As String
        
        '<remarks/>
        Public Occupation As String
        
        '<remarks/>
        Public Salary As Decimal
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public SalarySpecified As Boolean
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public DateOfHire As Date
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public DateOfHireSpecified As Boolean
        
        '<remarks/>
        Public Height_FT As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Height_FTSpecified As Boolean
        
        '<remarks/>
        Public Height_IN As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Height_INSpecified As Boolean
        
        '<remarks/>
        Public Weight As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public WeightSpecified As Boolean
        
        '<remarks/>
        Public HoursWorkedPerWeek As Decimal
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public HoursWorkedPerWeekSpecified As Boolean
        
        '<remarks/>
        Public Bonus As Decimal
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public BonusSpecified As Boolean
        
        '<remarks/>
        Public Duties As String
        
        '<remarks/>
        Public DataChangeDate As String
        
        '<remarks/>
        Public AnnWorkDays As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public AnnWorkDaysSpecified As Boolean
        
        '<remarks/>
        Public PinCode As String
        
        '<remarks/>
        Public County As String
        
        '<remarks/>
        Public Department As String
        
        '<remarks/>
        Public PayType As PayTypeList
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public PayTypeSpecified As Boolean
        
        '<remarks/>
        Public Shift As String
        
        '<remarks/>
        Public TaxRate As Decimal
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public TaxRateSpecified As Boolean
        
        '<remarks/>
        Public W4Expemt As Integer
        
        '<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public W4ExpemtSpecified As Boolean
        
        '<remarks/>
        Public LocationInfo As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/employeeinfo")>  _
    Public Enum EmployeeStateList
        
        '<remarks/>
        AK
        
        '<remarks/>
        AL
        
        '<remarks/>
        AR
        
        '<remarks/>
        AZ
        
        '<remarks/>
        BC
        
        '<remarks/>
        CA
        
        '<remarks/>
        CO
        
        '<remarks/>
        CT
        
        '<remarks/>
        DC
        
        '<remarks/>
        DE
        
        '<remarks/>
        FL
        
        '<remarks/>
        GA
        
        '<remarks/>
        GU
        
        '<remarks/>
        HI
        
        '<remarks/>
        IA
        
        '<remarks/>
        ID
        
        '<remarks/>
        IL
        
        '<remarks/>
        [IN]
        
        '<remarks/>
        KS
        
        '<remarks/>
        KY
        
        '<remarks/>
        LA
        
        '<remarks/>
        MA
        
        '<remarks/>
        MD
        
        '<remarks/>
        [ME]
        
        '<remarks/>
        MI
        
        '<remarks/>
        MN
        
        '<remarks/>
        MO
        
        '<remarks/>
        MS
        
        '<remarks/>
        MT
        
        '<remarks/>
        NA
        
        '<remarks/>
        NC
        
        '<remarks/>
        ND
        
        '<remarks/>
        NE
        
        '<remarks/>
        NH
        
        '<remarks/>
        NJ
        
        '<remarks/>
        NM
        
        '<remarks/>
        NV
        
        '<remarks/>
        NY
        
        '<remarks/>
        OH
        
        '<remarks/>
        OK
        
        '<remarks/>
        [ON]
        
        '<remarks/>
        [OR]
        
        '<remarks/>
        PA
        
        '<remarks/>
        PR
        
        '<remarks/>
        RI
        
        '<remarks/>
        SC
        
        '<remarks/>
        SD
        
        '<remarks/>
        TN
        
        '<remarks/>
        TX
        
        '<remarks/>
        UT
        
        '<remarks/>
        VA
        
        '<remarks/>
        VI
        
        '<remarks/>
        VT
        
        '<remarks/>
        WA
        
        '<remarks/>
        WI
        
        '<remarks/>
        WV
        
        '<remarks/>
        WY
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/employeeinfo")>  _
    Public Enum EmployeeGender
        
        '<remarks/>
        Male
        
        '<remarks/>
        Female
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/employeeinfo")>  _
    Public Enum EmployeeMaritalStatus
        
        '<remarks/>
        Unknown
        
        '<remarks/>
        [Single]
        
        '<remarks/>
        Married
        
        '<remarks/>
        Divorced
        
        '<remarks/>
        Separated
        
        '<remarks/>
        Widow
        
        '<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("N/A")>  _
        NA
    End Enum
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.plane.biz/exchange/20060125/employeeinfo")>  _
    Public Enum PayTypeList
        
        '<remarks/>
        Unknown
        
        '<remarks/>
        Hourly
        
        '<remarks/>
        Salary
    End Enum
End Namespace
